version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - deployment-net

networks:
  deployment-net:
    external: true
      